### ISSUE TITLE
Link discord on README.md

### ISSUE THREAD

**Issue by sirNikolai** [DAHP-MC/Spells-Api#12]
### Details of Feature
Add a badge for https://discord.gg/harrypotter on the README.md

### Possible Dependencies Needed for Feature
N/A

### New Commands Included in Feature
N/A

**Comment by hms5232** [comment]
I want to try it.

**Comment by HammedBabatunde** [comment]
Can I work on this issue.

**Comment by sirNikolai** [comment]
Sure. I believe either shields.io or something similar should have presets that can be added.

**Comment by sirNikolai** [comment]
Had to get this rolled out for tonight so was done on a different PR.
