### ISSUE TITLE
Add pom.xml dependencies

### ISSUE THREAD

**Issue by sirNikolai** [DAHP-MC/Spells-Api#16]
### Details of Feature
Add existing POM dependencies from spells into spells API to be utilized.
These do not require tests, but project should compile and not have any breaking changes.
This issue is mainly just for the imports in maven, do not actually need to do any code.

### Possible Dependencies Needed for Feature
The following are needed to be added:
- [x] [ProtocolLib](https://github.com/dmulloy2/ProtocolLib/)
- [x] [Vault API](https://github.com/MilkBowl/VaultAPI)
- [x] [Libs Disguises](https://github.com/libraryaddict/LibsDisguises)
- [ ] [WorldGuard](https://worldguard.enginehub.org/en/latest/developer/dependency/)
- [ ] [WorldEdit](https://www.spigotmc.org/wiki/setting-up-the-worldedit-api/)
- [x] [Player Particles](https://github.com/Esophose/PlayerParticles)

### New Commands Included in Feature
N/A

**Comment by govindraj111** [comment]
@sirNikolai can I work on this? Please assign this issue to me!

**Comment by govindraj111** [comment]
Review the PR #17
